/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "consultant" | "contributor" | "platform_admin" | "recipient" | "reviewer";

export type UserStatus = "active" | "deactivated" | "invited";

export interface AppUser {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deactivated_at: Timestamp | null;
  display_name: string;
  email: string;
  id: Generated<string>;
  password_hash: string | null;
  role: UserRole;
  status: Generated<UserStatus>;
  tenant_id: string;
  totp_enabled_at: Timestamp | null;
  totp_secret_enc: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface AuditAuditLog {
  action: string | null;
  actor_role: string | null;
  actor_user_id: string;
  changed_fields: string[] | null;
  client_id: string | null;
  id: Generated<Int8>;
  new_row: Json | null;
  occurred_at: Generated<Timestamp>;
  old_row: Json | null;
  op: string;
  reason: string | null;
  record_id: string | null;
  request_id: string | null;
  table_name: string;
  tenant_id: string | null;
}

export interface Client {
  address_line1: string;
  address_line2: string | null;
  city: string;
  contact_email: string;
  contact_name: string;
  contact_phone: string | null;
  country_code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  legal_name: string;
  postcode: string | null;
  registration_no: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ClientFactorOverride {
  client_id: string;
  component: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  id: Generated<string>;
  justification: string;
  kind: string;
  region: string | null;
  si_unit: string;
  source: string;
  status: Generated<string>;
  subject: string;
  tenant_id: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  valid_from: string;
  valid_to: string | null;
  value: Numeric;
  value_si: Numeric;
  year: number | null;
}

export interface CnCode {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  description: string;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface EuImporter {
  address_line1: string | null;
  city: string | null;
  client_id: string;
  contact_email: string | null;
  contact_name: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  eori: string;
  id: Generated<string>;
  name: string;
  postcode: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface EvidenceDocument {
  bytes: Int8;
  client_id: string;
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  doc_type: string;
  document_date: string | null;
  file_name: string;
  id: Generated<string>;
  installation_id: string | null;
  sha256: string;
  storage_key: string;
  tenant_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface EvidenceLink {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  evidence_id: string;
  id: Generated<string>;
  installation_id: string | null;
  period_version_id: string | null;
  record_id: string;
  record_table: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface GoodsCategory {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  indirect_relevant_definitive: boolean;
  indirect_relevant_transitional: boolean;
  library_version_id: string;
  name: string;
  route_relevant: boolean;
  sector: string;
  sort_order: number;
  template_name: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface Installation {
  auth_rep_email: string | null;
  auth_rep_name: string | null;
  auth_rep_phone: string | null;
  city: string;
  client_id: string;
  country_code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  economic_activity: string | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name_en: string;
  name_local: string | null;
  permit_no: string | null;
  po_box: string | null;
  postcode: string | null;
  street: string;
  tenant_id: string;
  un_locode: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface Invitation {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  tenant_id: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface LibraryFactor {
  component: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  kind: string;
  library_version_id: string;
  notes: string | null;
  plausible_max: Numeric | null;
  plausible_min: Numeric | null;
  region: string | null;
  si_unit: string;
  source: string;
  subject: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  valid_from: string;
  valid_to: string | null;
  value: Numeric;
  value_si: Numeric;
  year: number | null;
}

export interface LibraryImport {
  applied_at: Timestamp | null;
  base_fingerprint: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  dataset: string;
  file_name: string;
  file_sha256: string;
  id: Generated<string>;
  library_version_id: string;
  row_count: number;
  rows: Json;
  status: Generated<string>;
  summary: Json;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface LibrarySetting {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  key: string;
  library_version_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  value: Numeric;
}

export interface LibraryVersion {
  based_on_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  notes: string | null;
  published_at: Timestamp | null;
  published_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface PeriodStatusChange {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  from_status: string | null;
  id: Generated<string>;
  installation_id: string;
  period_version_id: string;
  reason: string | null;
  tenant_id: string;
  to_status: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface PeriodVersion {
  approved_at: Timestamp | null;
  approved_by: string | null;
  based_on_version_id: string | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  installation_id: string;
  issued_at: Timestamp | null;
  issued_by: string | null;
  library_version_id: string;
  period_id: string;
  status: Generated<string>;
  template_version_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  version_no: number;
}

export interface ProcessGood {
  client_id: string;
  cn_code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  installation_id: string;
  library_version_id: string;
  period_version_id: string;
  process_id: string;
  produced_default_ref: string | null;
  produced_provenance: string | null;
  produced_si: Numeric | null;
  produced_source: string | null;
  produced_unit: string | null;
  produced_value: Numeric | null;
  product_name: string | null;
  sold_eu_default_ref: string | null;
  sold_eu_provenance: string | null;
  sold_eu_si: Numeric | null;
  sold_eu_source: string | null;
  sold_eu_unit: string | null;
  sold_eu_value: Numeric | null;
  sold_other_default_ref: string | null;
  sold_other_provenance: string | null;
  sold_other_si: Numeric | null;
  sold_other_source: string | null;
  sold_other_unit: string | null;
  sold_other_value: Numeric | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ProcessGoodParameter {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  good_id: string;
  goods_category_code: string;
  id: Generated<string>;
  installation_id: string;
  library_version_id: string;
  period_version_id: string;
  position: number;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  value_default_ref: string | null;
  value_provenance: string | null;
  value_si: Numeric | null;
  value_source: string | null;
  value_text: string | null;
  value_unit: string | null;
  value_value: Numeric | null;
}

export interface ProcessIncludedCategory {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  installation_id: string;
  library_version_id: string;
  period_version_id: string;
  process_id: string;
  route_codes: Generated<string[]>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ProcessInternalUse {
  amount_default_ref: string | null;
  amount_provenance: string | null;
  amount_si: Numeric | null;
  amount_source: string | null;
  amount_unit: string | null;
  amount_value: Numeric | null;
  client_id: string;
  consumer_process_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  installation_id: string;
  library_version_id: string;
  period_version_id: string;
  process_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ProcessRoute {
  amount_default_ref: string | null;
  amount_provenance: string | null;
  amount_si: Numeric | null;
  amount_source: string | null;
  amount_unit: string | null;
  amount_value: Numeric | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  installation_id: string;
  library_version_id: string;
  period_version_id: string;
  process_id: string;
  route_code: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ProductionProcess {
  client_id: string;
  completed_at: Timestamp | null;
  completed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  installation_id: string;
  library_version_id: string;
  name: string;
  non_cbam_default_ref: string | null;
  non_cbam_provenance: string | null;
  non_cbam_si: Numeric | null;
  non_cbam_source: string | null;
  non_cbam_unit: string | null;
  non_cbam_value: Numeric | null;
  period_version_id: string;
  position: number;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ProductionRoute {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  name: string;
  sort_order: number;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface QualifyingParameterDef {
  choices: string[] | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  dimension: string | null;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  name: string;
  position: number;
  required: boolean;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  value_kind: string;
}

export interface RefCountry {
  code: string;
  name: string;
  source: string;
}

export interface ReportingPeriod {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  end_date: string;
  id: Generated<string>;
  installation_id: string;
  justification: string | null;
  start_date: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface RouteRelevantPrecursor {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  precursor_category_code: string;
  route_code: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface TemplateVersion {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  file_name: string;
  file_sha256: string;
  id: Generated<string>;
  released_on: string;
  source: string;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface Tenant {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  is_platform_operator: Generated<boolean>;
  name: string;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface UserClientAssignment {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  user_id: string;
}

export interface UserInstallationAssignment {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  installation_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  user_id: string;
}

export interface Verification {
  accreditation_body: string | null;
  accreditation_member_state: string | null;
  accreditation_reg_no: string | null;
  client_approved_at: Timestamp | null;
  client_approved_by: string | null;
  client_id: string;
  consultant_approved_at: Timestamp | null;
  consultant_approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  findings: Generated<string[]>;
  id: Generated<string>;
  installation_id: string;
  opinion: string | null;
  period_version_id: string;
  rep_email: string | null;
  rep_fax: string | null;
  rep_name: string | null;
  rep_phone: string | null;
  site_visit_date: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  verifier_city: string | null;
  verifier_country_code: string | null;
  verifier_name: string | null;
  verifier_postcode: string | null;
  verifier_street: string | null;
}

export interface DB {
  app_user: AppUser;
  "audit.audit_log": AuditAuditLog;
  client: Client;
  client_factor_override: ClientFactorOverride;
  cn_code: CnCode;
  eu_importer: EuImporter;
  evidence_document: EvidenceDocument;
  evidence_link: EvidenceLink;
  goods_category: GoodsCategory;
  installation: Installation;
  invitation: Invitation;
  library_factor: LibraryFactor;
  library_import: LibraryImport;
  library_setting: LibrarySetting;
  library_version: LibraryVersion;
  period_status_change: PeriodStatusChange;
  period_version: PeriodVersion;
  process_good: ProcessGood;
  process_good_parameter: ProcessGoodParameter;
  process_included_category: ProcessIncludedCategory;
  process_internal_use: ProcessInternalUse;
  process_route: ProcessRoute;
  production_process: ProductionProcess;
  production_route: ProductionRoute;
  qualifying_parameter_def: QualifyingParameterDef;
  ref_country: RefCountry;
  reporting_period: ReportingPeriod;
  route_relevant_precursor: RouteRelevantPrecursor;
  template_version: TemplateVersion;
  tenant: Tenant;
  user_client_assignment: UserClientAssignment;
  user_installation_assignment: UserInstallationAssignment;
  verification: Verification;
}
