/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "consultant" | "contributor" | "platform_admin" | "recipient" | "reviewer";

export type UserStatus = "active" | "deactivated" | "invited";

export interface AppUser {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deactivated_at: Timestamp | null;
  display_name: string;
  email: string;
  id: Generated<string>;
  password_hash: string | null;
  role: UserRole;
  status: Generated<UserStatus>;
  tenant_id: string;
  totp_enabled_at: Timestamp | null;
  totp_secret_enc: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface AuditAuditLog {
  action: string | null;
  actor_role: string | null;
  actor_user_id: string;
  changed_fields: string[] | null;
  client_id: string | null;
  id: Generated<Int8>;
  new_row: Json | null;
  occurred_at: Generated<Timestamp>;
  old_row: Json | null;
  op: string;
  reason: string | null;
  record_id: string | null;
  request_id: string | null;
  table_name: string;
  tenant_id: string | null;
}

export interface Client {
  address_line1: string;
  address_line2: string | null;
  city: string;
  contact_email: string;
  contact_name: string;
  contact_phone: string | null;
  country_code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  legal_name: string;
  postcode: string | null;
  registration_no: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ClientFactorOverride {
  client_id: string;
  component: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  id: Generated<string>;
  justification: string;
  kind: string;
  region: string | null;
  si_unit: string;
  source: string;
  status: Generated<string>;
  subject: string;
  tenant_id: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  valid_from: string;
  valid_to: string | null;
  value: Numeric;
  value_si: Numeric;
  year: number | null;
}

export interface CnCode {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  description: string;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface EuImporter {
  address_line1: string | null;
  city: string | null;
  client_id: string;
  contact_email: string | null;
  contact_name: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  eori: string;
  id: Generated<string>;
  name: string;
  postcode: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface GoodsCategory {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  indirect_relevant_definitive: boolean;
  indirect_relevant_transitional: boolean;
  library_version_id: string;
  name: string;
  route_relevant: boolean;
  sector: string;
  sort_order: number;
  template_name: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface Installation {
  auth_rep_email: string | null;
  auth_rep_name: string | null;
  auth_rep_phone: string | null;
  city: string;
  client_id: string;
  country_code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  deleted_at: Timestamp | null;
  economic_activity: string | null;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name_en: string;
  name_local: string | null;
  permit_no: string | null;
  po_box: string | null;
  postcode: string | null;
  street: string;
  tenant_id: string;
  un_locode: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface Invitation {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  tenant_id: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface LibraryFactor {
  component: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  kind: string;
  library_version_id: string;
  notes: string | null;
  plausible_max: Numeric | null;
  plausible_min: Numeric | null;
  region: string | null;
  si_unit: string;
  source: string;
  subject: string;
  unit: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  valid_from: string;
  valid_to: string | null;
  value: Numeric;
  value_si: Numeric;
  year: number | null;
}

export interface LibraryImport {
  applied_at: Timestamp | null;
  base_fingerprint: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  dataset: string;
  file_name: string;
  file_sha256: string;
  id: Generated<string>;
  library_version_id: string;
  row_count: number;
  rows: Json;
  status: Generated<string>;
  summary: Json;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface LibraryVersion {
  based_on_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  notes: string | null;
  published_at: Timestamp | null;
  published_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface ProductionRoute {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  name: string;
  sort_order: number;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface QualifyingParameterDef {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  name: string;
  position: number;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface RefCountry {
  code: string;
  name: string;
  source: string;
}

export interface RouteRelevantPrecursor {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  goods_category_code: string;
  id: Generated<string>;
  library_version_id: string;
  precursor_category_code: string;
  route_code: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface TemplateVersion {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  file_name: string;
  file_sha256: string;
  id: Generated<string>;
  released_on: string;
  source: string;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface Tenant {
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  is_platform_operator: Generated<boolean>;
  name: string;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
}

export interface UserClientAssignment {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  user_id: string;
}

export interface UserInstallationAssignment {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: Generated<string>;
  id: Generated<string>;
  installation_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<string>;
  user_id: string;
}

export interface DB {
  app_user: AppUser;
  "audit.audit_log": AuditAuditLog;
  client: Client;
  client_factor_override: ClientFactorOverride;
  cn_code: CnCode;
  eu_importer: EuImporter;
  goods_category: GoodsCategory;
  installation: Installation;
  invitation: Invitation;
  library_factor: LibraryFactor;
  library_import: LibraryImport;
  library_version: LibraryVersion;
  production_route: ProductionRoute;
  qualifying_parameter_def: QualifyingParameterDef;
  ref_country: RefCountry;
  route_relevant_precursor: RouteRelevantPrecursor;
  template_version: TemplateVersion;
  tenant: Tenant;
  user_client_assignment: UserClientAssignment;
  user_installation_assignment: UserInstallationAssignment;
}
